### ISSUE TITLE
Install plugins locally - Invalid plugin manifest

### ISSUE THREAD

**Issue by purpl3F0x** [Inrixia/neptune-plugins#1]
Hello, I try to build the plugins locally but when i select the dist/index.js from the dialog i get this message:

![image](https://github.com/Inrixia/neptune-plugins/assets/16735391/860b4f5a-d438-45cb-9bf1-d23c3234aade)

**Comment by Inrixia** [comment]
See this issue for further info. https://github.com/uwu/neptune-template/issues/1

Feel free to continue to ask questions here.
