### ISSUE TITLE
Question re. MQA tags and level of detail

### ISSUE THREAD

**Issue by heartmeeting** [Inrixia/neptune-plugins#10]
Firstly, this is a question rather than an issue and I'm delighted with the plugins - thanks so much for making them!

When I play an MQA album through my MQA certified DAC and get tags info - for example, 24 bit - 48khz - 1349kb/s - do you know at what point the khz reading is taken? i.e. before any unfolding as the pure CD, after the Tidal software has done the first unfold, or after the DAC has done its rendering? I am guessing it is one of the first two of these, but am wondering if it's possible to tell what level of unfolding is actually going on.

Whether you can advise or whether it's a "no idea" answer, I still love what you've done!

**Comment by Inrixia** [comment]
Sure, the reported Sample Rate, Bit Depth and Bitrate is all given using the FLAC metadata of the actual file (this is done by reading the first 43 bytes of the song where this Metadata is stored).

So the Sample Rate if it's a MQA file will be the base file's sample rate. Unfolding does not change Bitrate or Bit Depth.

If you want to know what Sample Rate you are getting after unfolding, just take the base sample rate and double it for software encoding, if you have a DAC that does "full unfolding" then I think it's 3x of 4x.

**Comment by Inrixia** [comment]
And Thanks! Glad you are enjoying it

**Comment by heartmeeting** [comment]
Sorry to reopen this - but another related question. When I use UAPP on my Android phone with an MQA file, it shows me the fully upsampled end product that my Dragonfly Red is playing at - i.e. the original sample rate at which the master was recorded which could be 176.4khz, 384khz, etc. I assumed this information was coming from the same file as your tags are picking up - is this something that could be added or am I holding entirely the wrong end of the stick? Thanks

**Comment by Inrixia** [comment]
I don't have any access to the actual player itself so can't get that information.

That said unfolding always goes to the max rate regardless of the track depending on the dac used so it's fairly easy to calculate the actual sample rate off the base.

**Comment by heartmeeting** [comment]
Thanks very much for clarifying - closing issue on that basis.
