### ISSUE TITLE
 How can I insert the "discnumber" tag?

### ISSUE THREAD

**Issue by jodong0704** [Inrixia/neptune-plugins#101]
https://tidal.com/browse/album/394023528?u

The album in the link above consists of two discs. 
However, if you use the downloader, the discs cannot be distinguished and are downloaded as one album.

The discnumber tag is not applied in fllename format, so I wonder if it is possible to add it.
![스크린샷 2024-11-12 132833](https://github.com/user-attachments/assets/a229b3c4-f87f-4f0f-b8f9-a91fe9fc15bf)

**Comment by Inrixia** [comment]
These are the tags available for use https://github.com/Inrixia/neptune-plugins/blob/0ca5ba60306fa293b767ec3736a43dd381c19c80/plugins/_lib/makeTags.ts#L68-L87

Looks like the volume isnt included in that metadata. Ill have to see about if its possible to include it etc.

**Comment by jodong0704** [comment]
Thank you for the quick reply.
In the case of the tidal-GUI program, it was downloaded separately into cd1 and cd2 folders.
Your program is very convenient, and it would be even better if you just added the disk number.

**Comment by Inrixia** [comment]
That's the plan
