### ISSUE TITLE
Song downloader not working with prompt

### ISSUE THREAD

**Issue by RealToasterBoi** [Inrixia/neptune-plugins#103]
Having issues with the song downloader when not using a default save location.  When I try to download songs the progress bar gets to the end, then nothing happens.  This was in the console: 
![image](https://github.com/user-attachments/assets/ac64fa39-bc71-4ee1-906e-0037d27c28fb)

**Comment by Inrixia** [comment]
You should be getting prompted if you don't specify a save location.

But if you are on Linux this may not be the case.

If you set a save location what happens?

Also that warning is unrelated.

I expect if you go to your tidal install location you will find downloaded songs there.

**Comment by Inrixia** [comment]
Thanks for letting me know what fixed it!

This will be useful for anyone else who runs into this.
