### ISSUE TITLE
Song Downloader does not populate metadata

### ISSUE THREAD

**Issue by CaptainDeSync** [Inrixia/neptune-plugins#104]
![image](https://github.com/user-attachments/assets/30dd9830-c32c-42a5-9def-0c14ac5a83fb)

Seems that something has broken with this since it on top of that, does not add the album art. Every song I've tried has done the same, so it shouldn't be exclusive. 

![image](https://github.com/user-attachments/assets/e573c047-d537-4758-9337-6cf13c7c9649)

**Comment by Inrixia** [comment]
Given the bitrate I assume this is a song that only has Low quality available. Unfortunately tagging for non flac files isnt supported.

**Comment by CaptainDeSync** [comment]
Ah, I see. I have it set to High quality so it doesn't fill up my drive so fast. I just tried it on high-res lossless and it seems to work. Thanks!
