### ISSUE TITLE
Volume Scroll not working after restart

### ISSUE THREAD

**Issue by gabriel-gfs** [Inrixia/neptune-plugins#106]
The volume scroll doesnt work after a restart sometimes. After an Update or when starting Tidal for the first time the scrolling doesnt work and only starts working again after disabling and reenabling the plugin.

**Comment by Inrixia** [comment]
Psure this is a ongoing issue with neptune plugins in general and should be opened on the Neptune repo.

Don't think there's anything we can do here for it sorry.
