### ISSUE TITLE
"read-only file system" notification in downloader plugin

### ISSUE THREAD

**Issue by jotacoro** [Inrixia/neptune-plugins#108]
### Configuration
> [!NOTE]  
This was reproduced using: <br> - Apple M1 Pro <br> - macOS 14.6.1 <br> - [neptune 1.0.0](https://github.com/uwu/neptune-installer/releases/tag/1.0.0) <br> - Tidal client version 2.38.5.68

### Steps to reproduce
1. Install neptune.
2. Install [Downloader plugin](https://github.com/Inrixia/neptune-plugins#downloader)
3. Try to download a song.

### Current behaviour
An error notification appears containing the text: `erofs read-only file system`.

### For avoiding
After setting a default path in the plugin settings, this error stop happening. 
![image](https://github.com/user-attachments/assets/7b8962dd-f497-4a7b-9e20-0b15e9196241)

Consider at least updating the readme file to tell users they should set a default path in the plugin settings before starting to use the plugin.

> [!WARNING]
This won't be reproducible if the plugin was correctly configured but you removed the default path from the settings to reproduce this issue.
----

Thanks for creating these fantastic tools 🫶

**Comment by Inrixia** [comment]
Actually by default it should prompt you for where to save files when downloading. If I had to guess this is a issue on MacOS where its failing to prompt and then trying to save the file to the Neptune install dir (which I assume is readonly)

Some people on Unix based systems have reported that the filesystem prompt just doesn't appear for them, I'm still not sure why.

The fix for this is ofc to just manually set the path. Unfortunately there isn't really any indication as to why the prompt doesn't show.

I presume that if you clear the default save path it doesn't start prompting you for where to save?

**Comment by jotacoro** [comment]
> If I had to guess this is a issue on MacOS where its failing to prompt and then trying to save the file to the Neptune install dir (which I assume is readonly)

you’re absolutely right. Sorry because I didn’t screenshot nor copy the full error message but I perfectly remember that it included the Neptune install dir.

> Some people on Unix based systems have reported that the filesystem prompt just doesn't appear for them, I'm still not sure why.

yay, actually that was my case. No prompt and error message.

> I presume that if you clear the default save path it doesn't start prompting you for where to save?

no idea. I also tried the following:
1. Set a default path.
2. Remove the default path.
3. Kill the tidal client.
4. Start the tidal client.

and prompt always appeared.

Maybe what’s happening is something like it has a different behavior because the path is set to “null”, “undefined”, whatever? When installing Neptune.
Then when reproducing the steps above the default path is set to an empty string?
Don’t know, just wondering

**Comment by Inrixia** [comment]
Just to double check, after clearing the default path it started working and prompting you?

**Comment by Inrixia** [comment]
I think I've found the issue. Will close this with that fix, please comment asking to re-open if prompts still aren't working or if anyone else stumbles upon this.

Thanks!
