### ISSUE TITLE
Unable to toggle plugins.

### ISSUE THREAD

**Issue by Cooooked** [Inrixia/neptune-plugins#12]
I just successfully installed neptune for the first time and installed Tidal Tags by Inrixia. I am unable to enable the plugin.

**Comment by Cooooked** [comment]
Restarting PC fixed the issue, something about the apps cache?

**Comment by Inrixia** [comment]
No idea, feel free to reopen if it crops up again but cant do anything without logs.

Its likely a neptune issue anyway
