### ISSUE TITLE
Causing Tidal app to go completely black

### ISSUE THREAD

**Issue by ockle** [Inrixia/neptune-plugins#13]
It seems that this plugin has started to cause the entire Tidal app to go black when skipping tracks. To reproduce, I skip forward, it works, I then skip back, and it all goes black - menu bar and all. Toggling the plugin off in the neptune settings stops this from happening.

**Comment by Inrixia** [comment]
Thanks I'll look into fixing this soon.

**Comment by Inrixia** [comment]
This is currently being caused by the ExtraArt plugin. So for now please disable that.

Everting else seems to be working fine.
