### ISSUE TITLE
Problem with Neptune in the Tidal app

### ISSUE THREAD

**Issue by Leon71Mitico** [Inrixia/neptune-plugins#17]
With today's latest Tidal update, Neptune has disappeared. I tried deleting Tidal and then redownloading it, but nothing.

**Comment by Inrixia** [comment]
Sounds like a issue with neptune specifically. Can you open a issue on its repo here https://github.com/uwu/neptune

**Comment by Leon71Mitico** [comment]
> Sounds like a issue with neptune specifically. Can you open a issue on its repo here https://github.com/uwu/neptune

Okay, thank you

**Comment by Inrixia** [comment]
For anyone stumbling upon this with the same issue see https://github.com/uwu/neptune/issues/15

I'll leave this open here till its sorted for visibility
