### ISSUE TITLE
Tidal Tags plugin broken with latest update

### ISSUE THREAD

**Issue by NightKnightGR** [Inrixia/neptune-plugins#18]
Not working after new update

**Comment by Inrixia** [comment]
Can you clarify if it's the plugin specifically or the Neptune client in general?

**Comment by NightKnightGR** [comment]
It's just the plugin.

**Comment by Inrixia** [comment]
Ah can you open a issue on the Neptune repo please :) thx

**Comment by Inrixia** [comment]
https://github.com/uwu/neptune

**Comment by Inrixia** [comment]
Mb, I'll take a look when I get the chance

**Comment by sunspot478** [comment]
Hello Inrixia,
First off, thank you for providing the Tidal Tags plugin.  I love it.  So yeah... I'm NOW running Tidal version  2.36.2.54.  It updated and I can't see anywhere that you can prevent it from doing so.    Tidal tag display is still working, but the bitrate text in the lower corner is no longer being displayed.
![image](https://github.com/Inrixia/neptune-plugins/assets/158432343/5aa9d71e-5dfc-4ee2-84e6-c5a72934ea97)
![image](https://github.com/Inrixia/neptune-plugins/assets/158432343/fca88762-4f9c-4581-8f4c-fc57d9fd2bbe)

I hope this helps.  Thanks again!
...Jamie

**Comment by Inrixia** [comment]
Thanks, that's super helpful. Ill probably get this fixed either tonight or tomorrow hopefully.

For now it might be a good idea to go to your settings and toggle off the flac display incase just to be safe.

**Comment by sunspot478** [comment]
Wow, lightning fast response.  =)
Suggestion completed.
Thanks again ...  That's a really awesome addition to Tidal and I really wanna make sure you know it's appreciated. 
Have a good night!

**Comment by sunspot478** [comment]
Hi, checking in on progress.  Also to get an idea of how widespread this is.  Is it just me and NightKnightGR?

**Comment by sunspot478** [comment]
I decided to do a clean wipe of Tidal completely (even into the registry) and reinstall.  When I started playing the first HiRes song, down where it shows the MAX|FLAC tag, I saw text very briefly flash and disappear.  I'm not sure if that was the bitrate info or not.  But something was being displayed there for about 100 ms and vanished.  This only happened first play. 
Not sure if that is relevent or not...

**Comment by Inrixia** [comment]
So sorry this took so long to get sorted

**Comment by sunspot478** [comment]
I would guess that this is NOT your job and that you do this as a ... hobby.  As such, there's no need for apologies.  I'm merely riding on your coding coattails and or that, I'm quite appreciative.  

So ... What do I need to do in order to get this working again?  Reinstall?

**Comment by sunspot478** [comment]
Oh.  Nothing.  It just works.  Bonus.  Hats off to you.  =)  Thank you

**Comment by sunspot478** [comment]
Uh oh ... It's broke again  =\  *runs for cover*

**Comment by Inrixia** [comment]
Rip, hopefully as easy a fix as last time. Thanks for letting me know

**Comment by NightKnightGR** [comment]
The updates keep breaking it. Now updates are a weekly thing so if it keeps
breaking don't stress yourself it's fine. Thanks for the work.

**Comment by sunspot478** [comment]
It would be awesome if Tidal had a setting that allowed you to NOT update if you wished.
I'm working on a fairly large musical project that pivots on being able to determine the bitrate of what I'm streaming off Tidal so I think I may need to find another way if this keeps breaking.
Thanks for the effort!

**Comment by Inrixia** [comment]
Yea sorry for the delay in getting stuff fixed.

Usually it'd be a same day thing but unfortunately have a lot of stuff going on atm.

**Comment by sunspot478** [comment]
Please don't get the impession I'm applying pressure or somehow ungrateful.  I'm sure this is probably a volunteer thing for you.  I think I would be safe to speak for everyone when I say that we all appreciate your work and have no issue with whatever you decide to do with this.  Drop a comment if/when you get it fixed.  Thanks again!

**Comment by Inrixia** [comment]
Looks like something in one of the new updates has made all the access tokens in the session storage null so I can no longer make authenticated web requests to Tidals api's (unless I can find another way to get ahold of the token).

Ironically with the mobile changes for FLAC the **Sample Rate** & **Bit Depth** are now included in the api response for track metadata meaning actually grabbing the FLAC files header would only be needed for **Bitrate**.

But the Tidal desktop app does not use or expose the Sample Rate or Bit Depth that is now returned so I cant get a handle on that info anyway which is stupid.

Ill have a look and see if there is a work around for either getting ahold of the info from the api response, or if there is another way to get ahold of the bearer token.

**Comment by Inrixia** [comment]
It's looking like unless there is something that can be done to fix https://github.com/uwu/neptune/issues/20 that the ability to get additional metadata wont be possible.

**Comment by sunspot478** [comment]
https://tidal.com/browse/track/30344038

=(

**Comment by Inrixia** [comment]
Latest allows you to manually provide a bearer token since tidal appears to have stopped storing it in the application state.
Afik currently there is no way to automatically fetch it sadly.

If you need help figuring out how to set it please discuss on #21
