### ISSUE TITLE
I'm getting mixed results depending on the view

### ISSUE THREAD

**Issue by HeadhunterKev** [Inrixia/neptune-plugins#19]
Wherever I'm looking at the tags I get different results depending on the view.
In my favorite tracks:
![image](https://github.com/Inrixia/neptune-plugins/assets/69607571/0cbd94ed-d1b1-440c-b6e9-4b2c57e43c57)
When I filter my favorite tracks:
![image](https://github.com/Inrixia/neptune-plugins/assets/69607571/fd5ea031-faf0-4a1a-b1e5-babe606684a1)
Your chrome plugin:
![image](https://github.com/Inrixia/neptune-plugins/assets/69607571/18178442-c973-4277-9b7c-9820b45d042b)

When I play the songs from K.I.Z, the viewed artist, the quality is only "HIGH" for all songs. It seems like the tags are wrong as soon as you filter for something.

**Comment by Inrixia** [comment]
Yep filtering breaks everything. I don't think there is a way to fix it due to how tidal filters tracks but I can check.

**Comment by HeadhunterKev** [comment]
The info would be great if we could read it somehow.
But you don't have to check it because of me. I'm quite disappointed how many tracks are even available in High Resolution and how they present this info. You shouldn't have to create a plugin for that, that should be standard!
I won't continue to use Tidal and get back to Spotify. Might not have the same quality but the user experience is much better.

Thank you for making the time I spent on Tidal much better, your plugin helped a lot!

**Comment by Inrixia** [comment]
I think it's worth nothing that untagged tracks in tidal are still HiFi quality (16bit 44.1kHz) which is standard high quality and still much better than Spotify which is always lossy encoded.

I fact all the qualities (except MQA) are lossless it just depends on the sample rate and bit depth given by the artist.

**Comment by Inrixia** [comment]
You might find reading this help clarify some things https://www.reddit.com/r/TIdaL/comments/15ifs6j/decoding_tidals_max_quality_update_what_the_heck/

**Comment by HeadhunterKev** [comment]
Yeah, I know about all of these audio quality differences. Your Reddit post was the way I found your plugin!
But the purpose of my issue was not bashing Tidal so I will stop that right here. I'm happy there are services that offer lossless audio quality. Spotify promised that a while ago and went silent for three years. And it will probably not come 2024 as well according to analysts.

**Comment by Inrixia** [comment]
Yea, it's a shame but I'm honestly hopeful that it gets it as currently I use both and bring able to consolidate like that would be great. 

Anyway thanks again for highlighting this issue I'll look into it when I get time
