### ISSUE TITLE
Song Downloader Has Stopped Functioning

### ISSUE THREAD

**Issue by Jasser1999** [Inrixia/neptune-plugins#21]
Tidal Desktop version **2.36.2**

I don't know if song downloader plugin was ready but, I have been using it for past 2 months. As of last week it looks like it stopped functioning as it gets stuck now on Fetching Meta.
![image](https://github.com/Inrixia/neptune-plugins/assets/155720060/9d035abc-5418-4949-a92a-e8c971ab781d)

**Comment by Inrixia** [comment]
This is related to #20 and #18. Im hoping to actually manage fixing this today.

Apologies for the delay

**Comment by Inrixia** [comment]
Latest allows you to manually provide a bearer token since tidal appears to have stopped storing it in the application state.

Afik currently there is no way to automatically fetch it sadly.

**Comment by Inrixia** [comment]
Please feel free to ask if you need help figuring out how to get it.

**Comment by Jasser1999** [comment]
> Please feel free to ask if you need help figuring out how to get it.

Got it to work , thank you for the quick update really love these plugins very nice QoL updates.

**Comment by sunspot478** [comment]
Hi,
From what I read, acquiring an access token to enter is a developer-only thing?

**Comment by Inrixia** [comment]
Nope, you just need to open the dev tools in neptune (Ctrl-Shift-I) and go to the network tab.

After this it's easiest to start playing a new song and then inspect the network requests looking for the Authentication header. You want the code after `Bearer`.

**Comment by sunspot478** [comment]
Hi Inrixia,

I'm sorry, I don't want to be a pest about this... I'm not able to find the 'Bearer' tag

![image](https://github.com/Inrixia/neptune-plugins/assets/158432343/8e00600f-5d52-4e36-8481-f221b7caf467)

Am I even in the right spot?  (Tidal app for PC)
Thanks

**Comment by Inrixia** [comment]
Your looking in the right spot. But only certain requests have the header.

Generally playing a new song will trigger one of those requests. Just click through a few and you should find it.

**Comment by sunspot478** [comment]
Oh!  Okay.  Fair enough.  Thanks for the quick response.  You're awesome

**Comment by Inrixia** [comment]
Hope it helps. Do reach out if you are still stuck and let me know if you get it working!

**Comment by Inrixia** [comment]
It's a real shame the token was removed from the application state recently. Just makes things neccearily difficult.

**Comment by Inrixia** [comment]
I'm gonna leave this open for visibility

**Comment by sunspot478** [comment]
Your little plugin there is useful - actually - essential for a musical project I'm completing.  If I can't determine the bitrate of what's playing, Tidal is really not useful to me.  I can get by with the 320kbps mps3 on Spotify.
Kinda nice that the Tidal family plan is going down in price in April.

**Comment by sunspot478** [comment]
Here's what I've found.  I've tried playing multiple songs on the Tidal desktop PC app and it does not show the Bearer tag in any events.  I then tried Tidal web player and it showed immediately under the "events" and "sessions" with a little gear to the left:

![image](https://github.com/Inrixia/neptune-plugins/assets/158432343/1b79303c-d229-41e8-8da9-2da6fb07ac47)

![image](https://github.com/Inrixia/neptune-plugins/assets/158432343/3235873f-0433-486e-9f75-62e8df7bbfae)

Unfortunately, the Bearer tag info does NOT work for the app if you place it in there.  It will unlock the switches, but they have no effect in the app.  The info still does not show. 

![image](https://github.com/Inrixia/neptune-plugins/assets/158432343/bfd2e2b3-75c6-48b6-8d8a-edbba9adb859)

**Comment by Inrixia** [comment]
@sunspot478 I edited your comment so the image with your token isnt easily visible. I don't recommend sharing that. 

You are looking for something like this:
![image](https://github.com/Inrixia/neptune-plugins/assets/6373693/2f05ffa6-969c-4490-9c93-ee57f8a58cdb)

Also when entering the token in settings make sure you only have the token itself, not including the `Bearer ` prefix.

**Comment by sunspot478** [comment]
AHA!  
First of all, thanks for looking out for me, there.  I appreciate that.

Second ... I finally got it.  Up above, where it shows filters:  Fetch/XHR JS CSS Img Media etc ... I had "Other" selected.  I had to select "All" to see the playinfo tag, and from there it was easy.

Thank you for the help, yet again.

**Comment by Inrixia** [comment]
Imo this issue has the relevant info required to get all this working. I'm just going to note here that I've made a discord similar to one for my other project if people wanted to be able to discuss things easier.

**[discord.com/invite/jK3uHrJGx4](https://discord.com/invite/jK3uHrJGx4)**

**Comment by sunspot478** [comment]
First off, I'm totally good with setting the Oauth token for this to work.  Just part of the process.
Second, It's interesting that there are some files that it still won't display the info for right away, but most do.  One of the examples I found were the first two tracks on the same album that wouldn't show the bitrate after setting the token.  I knew the token was correct though because the rest on that album worked and SongDownloader worked.  After a restart of Tidal, the bitrate info displayed correctly.
So if you've just set it and it's not working, try restarting Tidal!

**Comment by Inrixia** [comment]
Ah Yea the Metadata for songs is cached so it only has to fetch it once. There isn't really any cache validation so it's possible the cache could be polluted if the tokens invalid.

But as you say restarting it will easily fix that

**Comment by Inrixia** [comment]
As of the latest commit this has been fixed as fetching the OAuth token is now possible again! Thanks @twnlink for the help, much appreciated!
