### ISSUE TITLE
All MQA being reported at either 48kHz or 44.1kHz in TidalTags

### ISSUE THREAD

**Issue by heartmeeting** [Inrixia/neptune-plugins#23]
Hi - thanks for all the recent fixes to TidalTags.

I am finding that whilst FLAC and High songs are reporting accurately, all MQA songs are showing as either 44.1kHZ or 48kHz - and I know lots of them are sample rates of 96kHZ, 192kHZ and 384kHZ among them according to Roon - which I'm definitely trying to get rid of in favour of your excellent plugins!

Are you able to advise please? Thanks loads.

**Comment by Inrixia** [comment]
The flac info reports the flac files base info.

If the file is MQA then to determine the sample rate you just need to take the base sample rate reported and multiply it by 2 for software unfolding or more if you have hardware unfolding.

Also note that if a song has both MQA and HiRes Tidal will use the HiRes version.

I'll close this but please do continue to ask questions either here or on discord if you have any :)

**Comment by Inrixia** [comment]
You may find my writeup here also useful https://www.reddit.com/r/TIdaL/s/nbqVaQhAHo

**Comment by heartmeeting** [comment]
As ever, many thanks for your quick and useful response.

Best wishes,

Ben

*Benjamin Cazin*
*Chartered FCIPD*
