### ISSUE TITLE
Always Exclusive link typed and linked in error in Github - missing a letter

### ISSUE THREAD

**Issue by heartmeeting** [Inrixia/neptune-plugins#25]
Hi - this is one which I hope helps you (rather than one for me).

In the My Public Plugins section, you are showing the link as _Install Url: https://inrixia.github.io/neptune-plugins/AlwaysExlusive/_ which is missing the 'c' of 'exclusive' in both the link text and the link itself. Therefore in using the link as is, it fails within Neptune plugins in Tidal. Easily corrected there by adding the 'c' manually, but I thought you'd like to know so you can change the source on here. 

![image](https://github.com/Inrixia/neptune-plugins/assets/144740060/6d5b8538-9312-45b1-929e-ceac6db6e577)

Hope that's useful - best wishes.

**Comment by Inrixia** [comment]
Thx! I'll get around to fixing this sometime soon :)

**Comment by heartmeeting** [comment]
Oops I wasn't clear - I pasted it as is into the Neptune plug inside in Tidal and added the c - and it works fine.

Thanks again!
