### ISSUE TITLE
Song downloader: "Component ContextMenuAction has not been captured yet"

### ISSUE THREAD

**Issue by RealToasterBoi** [Inrixia/neptune-plugins#26]
having the following issue with the song downloader: 
![2024-05-08 03_02_56-TIL FURTHER NOTICE (feat  James Blake   21 Savage) - Travis Scott, James Blake, ](https://github.com/Inrixia/neptune-plugins/assets/49450826/d6de8708-21d7-425c-8cc6-96a53b669fbd)

**Comment by Inrixia** [comment]
Very weird, I should have time to debug this tomorrow. Probably broken due to a recent ui update.

**Comment by Inrixia** [comment]
Is this still occurring? I cant reproduce this issue, have you tried reinstalling the plugin/Tidal/Neptune?
