### ISSUE TITLE
Unable to enable plugins

### ISSUE THREAD

**Issue by Crypto-Spartan** [Inrixia/neptune-plugins#27]
Hi,

I successfully installed Neptune, and I added your Shazam & Tidal Tags plugins. Unfortunately I can't toggle them on, they're stuck in this disabled state:

![image](https://github.com/Inrixia/neptune-plugins/assets/29098151/9b34faf0-b1bd-41a7-937a-a600703009e4)

Any help you could provide would be great! Thanks!

**Comment by Inrixia** [comment]
Closing re discord discussion, this is on @twnlink
