### ISSUE TITLE
Feature Request for TidalTags: Tag `High` & `Low` just like `HiRes` is tagged currently

### ISSUE THREAD

**Issue by Crypto-Spartan** [Inrixia/neptune-plugins#29]
Right now, the `HiRes` tag appears, but no other tag appears for tracks of other qualities (besides the `MQA` tag). It would be nice to have a tag for `High` and `Low` quality as well.

**Comment by Inrixia** [comment]
Re discord low is added and high won't be due to clutter and that you can infer since most songs are.
