### ISSUE TITLE
Need to disable and re-enable Tidal tags after opening/closing Tidal

### ISSUE THREAD

**Issue by kegobass** [Inrixia/neptune-plugins#3]
The slider is enabled for Tags but not working upon closing the app and relaunching.  If I turn off the slider, then re-enable, it works again.

Tidal Desktop version:  2.34.3.26

Thanks!

![image](https://github.com/Inrixia/neptune-plugins/assets/59669068/31f42915-7b74-4ce0-9e7d-a3da8afebc33)

![image](https://github.com/Inrixia/neptune-plugins/assets/59669068/627b03f7-4943-4938-ab33-64ad74a3c5af)

I move the slider for Tags off, then off and they work again:

![image](https://github.com/Inrixia/neptune-plugins/assets/59669068/46071fb1-ee34-458f-ad3a-ed73cfad62b0)

**Comment by Inrixia** [comment]
Can you hit ctrl-shift-i and go to console when its not working. Are there any logs that are red?

**Comment by Inrixia** [comment]
Try the latest version, there has been a lot of improvements recently that may have fixed this.

**Comment by kegobass** [comment]
Yep, the issue is no longer happening since the update.  Thanks!
