### ISSUE TITLE
SongDownloader - Unable to download single track

### ISSUE THREAD

**Issue by sunspot478** [Inrixia/neptune-plugins#32]
Hello!
Love the new improvements to SongDownloader and TidalTags.  

Small problem with SD.  Unable to download one single track (or a few...)  The option is not showing up on right click:

![image](https://github.com/Inrixia/neptune-plugins/assets/158432343/44e9533a-5cf0-4cd4-861e-0ac7b6a3d0f4)

But you can choose to download all in the "... More" at the top right of Add, Credits, Share

![image](https://github.com/Inrixia/neptune-plugins/assets/158432343/2b78edb0-0162-4281-927c-f64680fb973e)

Is this happening for you?
...Jamie

**Comment by Inrixia** [comment]
Thanks! This is due to a recent change I made. Fixed now.

In the future if you want a faster response ping me on discord, otherwise I can be a while before I notice issues appearing :)

**Comment by sunspot478** [comment]
Hah!  Ya, because you know a 19 minute resolution is REALLY slackin'.  Are you kidding me?  =)
You're like frickin' LIGHTNING!
Thanks for the quick resolution.
