### ISSUE TITLE
Use RealMAX Plugin to Automatically Upgrade Playlist Song Quality

### ISSUE THREAD

**Issue by Exspecto322** [Inrixia/neptune-plugins#33]
Noticed with the plugin that some of the songs I have in my playlists are not in the best quality, was wondering if it was possible to replace lower quality songs in a playlist, this would work great when transfering playlist from Spotify or others with 3rd party apps that just don't always add the best quality song.
I also noticed that the song usseewa - ado was one song that had a higher quality version and was not skipped to the high quality one with the plugin.
this made me realize too that, I had some songs in Dolby Atmos and that was not intended by my part either (tags plugin is great btw), would be cool to add a feature like a toggle option that could skip/change those too.

**Comment by Inrixia** [comment]
Can you link me the song in question that failed to upgrade? 
Its most likely that tidal does not have the valid metadata to properly lookup all versions of it... 
Sadly very common there is a lot of background black magic that goes into it for both RealMAX and last.fm.

If its not that though it'd be good to see if you have stumbled upon a edge case!

As for the ability to upgrade songs in playlists, that should be doable. Ill need to do a test to see but great idea!

**Comment by Exspecto322** [comment]
I had this song in the playlist:
https://tidal.com/browse/track/158798461?u
and it seems it has two better versions, 
the album one: https://tidal.com/browse/track/213033628?u
and this single one: https://tidal.com/browse/track/189737441?u

**Comment by Inrixia** [comment]
Yep https://tidal.com/browse/track/158798461 has no **isrc** info, its album does have a **upc** but sadly the musicbrainz api does not have an **isrc** for its version of the track so there is no way to look it up.

**Comment by Inrixia** [comment]
Latest version now lets you generate a copy of the given resource (Track/Tracks/Album/Playlist) same format as the Download button.

It will make a new playlist off the resources name and populate it with the tracks placing the max quality ones it finds if any in the proper place.

Decided to not do editing playlists in place because not only was it going to be a mess, but I don't like the idea of having any code modifying users playlists, too easy to break things.
