### ISSUE TITLE
Plugins won't turn on or stay on 

### ISSUE THREAD

**Issue by heartmeeting** [Inrixia/neptune-plugins#34]
I'm not sure what's changed since yesterday with Tidal, but my Neptune plugins have toggled off and can't be turned back on...

A couple are working, although the ones which are off obviously aren't.

Occasionally the off ones do toggle to on, but don't actually function.

I've uninstalled Neptune (2023 last update) and all the plugins individually and then reinstalled them all, after reinstalling Tidal, although I don't believe there's been a new Tidal release since before this started.

Are you also experiencing this?

![image](https://github.com/Inrixia/neptune-plugins/assets/144740060/0bb0973c-6c5a-4e99-87d6-470e825ce5c3)

**Comment by Inrixia** [comment]
Re the discord announcement currently most plugins are not going to work until I update them, this is fine and actually a good thing! 

Thanks  to the amazing work from @twnlink native side support is now in Neptune. This opens up a ton of possibilities for more things I can do as previously I only had access to the renderer/display side of things.

I'll give a update in #announcements in discord and close this once I have migrated the plugins so you know you can update.

Thanks for reporting it here though <3

**Comment by Inrixia** [comment]
Everything except Shazam should now be updated and working!
