### ISSUE TITLE
Long playlist won't work with RealMAX

### ISSUE THREAD

**Issue by Exspecto322** [Inrixia/neptune-plugins#35]
When creating a playlist with RealMAX, it stops at around 30 songs more or less, sometimes it goes up to around 60, it seems stops when showing the message "This playlist has been modified elsewhere, please refresh this page to get the latest version"

**Comment by Inrixia** [comment]
RealMAX now generates a single playlist at the end with all tracks and logs its process. 

Probably needs better logging its kinda spammy atm and there is no way to cancel it.
