### ISSUE TITLE
realMAX doesn't detect the higher quality tracks from Bastard by Tyler, the Creator

### ISSUE THREAD

**Issue by justtoask** [Inrixia/neptune-plugins#36]
So the title track, "French" & "VCR Wheels" from the album "Bastard" by Tyler, the Creator are also available on "12 Odd Future Songs" by Odd Future (a group that Tyler was a part of) and this release has the tracks uploaded in MAX (MQA) quality.

**Comment by Inrixia** [comment]
Unfortunately some tracks just won't be detected. This is due to said track not having any isrc or upc code set on Tidals end which makes it impossible to look up alternate versions.

Nothing I can do on this as it's a limitation on Tidals end sadly so I'll close this, but thanks.
