### ISSUE TITLE
[Bug] [TidalTags] Some songs don't get their info filled up after playing

### ISSUE THREAD

**Issue by Skubers** [Inrixia/neptune-plugins#38]
![image](https://github.com/user-attachments/assets/cf52b1e6-f3b6-4229-8ccc-d0a0a7ed58db)

https://tidal.com/browse/track/64494266?u

I suppose that's because RealMAX replaces the playing song with the higher version one, thus the one I have in my playlist doesn't get filled up with info

**Comment by Inrixia** [comment]
That's most likely the reason if you can verify that RealMAX is indeed running for that song.

Playlist filling has been a idea for a while though it would require hitting the api in a way that I don't think would mercenarily be appropriate.

Your best bet is to disable realmax and skip through or just skip through.

**Comment by Inrixia** [comment]
Could you link the playlist? Id like to double check what's going on with that song

**Comment by Skubers** [comment]
> Could you link the playlist? Id like to double check what's going on with that song

Sorry for late reply, there you go:

https://tidal.com/playlist/de19612c-c0d3-440b-bef7-f1ccbc30faa9

**Comment by Skubers** [comment]
Actually, with that playlist, you can see another issue where some entries in the playlist don't adjust to the new table arrangement:

![image](https://github.com/user-attachments/assets/ac727cca-8fa3-4208-82dc-8cae1b75ef52)

**Comment by Inrixia** [comment]
How are you changing the table alignment? Due to how elements are added there isnt much I can do to fix that.

**Comment by Inrixia** [comment]
Also regarding the initial issue. I think this is actually due to tidal disabling MQA tracks but still having the quality reported via their API.

**Comment by Inrixia** [comment]
MQA is no longer reported by the Tidal API, thus this issue can no longer occur.
