### ISSUE TITLE
would it be posible to add tidal live to pc tidal 

### ISSUE THREAD

**Issue by Pickymarker** [Inrixia/neptune-plugins#4]
would it be posible to add tidal live to pc tidal because this would be good to have once tidal neptune gets fixed for me

**Comment by Inrixia** [comment]
What's TIDAL live? I can probably look into it

**Comment by Inrixia** [comment]
Just looked into it. It would likely require reverse engineering a lot of the TIDAL API and maybe need mobile auth keys. I think this is way out of scope sadly.
