### ISSUE TITLE
[Bug] [DiscordRPC] Song shows as paused when loading

### ISSUE THREAD

**Issue by n1ckoates** [Inrixia/neptune-plugins#41]
When switching tracks, the song will show as "paused" in the activity while the next one is loading, because the current song pauses until then. This looks a bit weird, makes unnecessary RPC updates (which can get you ratelimited if you switch songs a ton) - and, if you have "clear on pause" enabled, briefly makes your presence disappear.

Not sure what the best way to fix this is. We need to somehow know that the next song is loading and not just paused.

**Comment by Inrixia** [comment]
A track transition can be known from this event firing https://github.com/Inrixia/neptune-plugins/blob/master/plugins%2FDiscordRPC%2Fsrc%2Findex.ts#L36

Though I'm unsure if the playback state is only paused during this specific event. If not may need to have some additional logic for identifying the intermediary pause state.

If you want to investigate it further you can use my testing plugin (use the normal url schema and replace the plugin name seen in the plugins folder) to see what events are firing and their payloads.
