### ISSUE TITLE
Ensure voby components are wrapped in @neptune/components/ReactiveRoot

### ISSUE THREAD

**Issue by twnlink** [Inrixia/neptune-plugins#5]
Any type of reactive computation (e.g `$()` calls, `useEffect`, etc) needs to be cleaned up upon being removed from the DOM by React.

To do so, make a component:
```js
function MyComponentName() {
  const state = $("state :D")

  return html`<div>hi</div>`
}
```

Then, wrap that component in:
```js
element.appendChild(ReactiveRoot({ children: MyComponentName }))
```
Upon removal from the DOM, all computations will be cleaned up.

This is to avoid memory leaks and performance issues.

**Comment by Inrixia** [comment]
Sweet, will make sure I do this. Is there a reason for using voby over React?

**Comment by twnlink** [comment]
React's model makes a lot less sense in the context of hooking into and swapping out existing UI, since React components are not *just* DOM nodes. Voby components *are* just DOM nodes and can easily be treated as such. I would've picked SolidJS but that requires a build step and I wanted to make unbuilt local plugins a possibility.

**Comment by Inrixia** [comment]
Right that makes total sense. I figured it would be along those lines.

Thanks again
