### ISSUE TITLE
[Bug] [DiscordRPC] "Play the song" button not showing anymore

### ISSUE THREAD

**Issue by ik0zy** [Inrixia/neptune-plugins#50]
![image](https://github.com/user-attachments/assets/ad0710b2-8398-4ec8-a799-47bba3d87c7a)

**Comment by Inrixia** [comment]
And you have the setting to display the button enabled?

Fairly sure this is a big on discords end

**Comment by ik0zy** [comment]
Yes, I have it enabled on the plugin settings.

**Comment by Inrixia** [comment]
The button still works fine for other people so I'm fairly sure this is a discord issue.

Sometimes discord rpc buggs out. A system restart and waiting a bit of time should fix it.

If not there isn't much I can really think of sorry.

I'm going to close this for now but if anyone else encounters this issue, or if it doesn't fix itself in a few days please let me know.

**Comment by n1ckoates** [comment]
This is a Discord bug, you can't see a button on your own activity if it's a listening one. If other people view your profile, or if you view it from a different client, you'll be able to see it.

**Comment by Inrixia** [comment]
Thanks for the clarification much appreciated
