### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by Araxeus** [Inrixia/neptune-plugins#56]
would be nice if plugins had version, that are also written in the plugin description

that way users can know which version are they running, and check whats the latest version available

I have enabled this behavior in my userscript:

![image](https://github.com/user-attachments/assets/b426b95a-fb1f-4ea4-9379-a2dac2dbd9ee)

https://github.com/Araxeus/tidal-neptune-plugins/blob/306c01fa9bbfd3e4d18de94509da374d97093521/volume-scroll/build.ts#L26-L35

> btw i still dont understand when exactly does neptune update the plugins, it seems like I need to manually remove it and add again

**Comment by Inrixia** [comment]
I don't maintain neptune so neptune side support isn't there.

Also plugins always use the latest version. Restarting your client will cause all plugins to update and there is no way to use older versions (unless I had the repo build older commits on paths which I won't)

**Comment by Inrixia** [comment]
It would be cool to maybe have the plugin have a reference to the commit that last changed it. But that would be painful to implement.

If you wanted to look into that then that would be cool though.

Otherwise I'll probably close this as not planned.

**Comment by Araxeus** [comment]
> I don't maintain neptune so neptune side support isn't there.

you dont need neptune to support it, you just maintain a version number for each plugin and insert it into the plugin description, I think its nice that you can know which version you have

**Comment by Inrixia** [comment]
I do agree. But I wouldn't want to be maintaining versioning for plugins it'd need to be automated which is why having it use the commit hash url would be great.

But it'd need to be done so that the hash url is relevant to the commit that last modified thst plugin.

And considering many of my plugins have core code in my shared lib tracking that would be a nightmare.

**Comment by Inrixia** [comment]
But alsy the version number would always be displaying the latest because unless you are offline the Neptune client will load the latest version every time it opens.

**Comment by Araxeus** [comment]
you can change the whole automation process to only happen when a version change

and then you can push many commit without posting a new version

> But alsy the version number would always be displaying the latest because unless you are offline the Neptune client will load the latest version every time it opens.

and then that would enable users to load a specific version, dont know how userful that is

anyway this is way out of scope, you would need to completely rework your automation process for very little benefit

**Comment by Inrixia** [comment]
Tbf if I wanted to do that I'd just use a seperate dev branch and merge releases into main to be deployed.

But I've never really had a need to yet.

Appreciate the idea though
