### ISSUE TITLE
Cover Themes black bars

### ISSUE THREAD

**Issue by Araxeus** [Inrixia/neptune-plugins#62]
Theres a big black bar in "My Profile"

![image](https://github.com/user-attachments/assets/c56c9e59-4608-4135-aa23-17c0f92c578a)

also playlist headers are black:

![image](https://github.com/user-attachments/assets/73708f93-cf62-4295-b8fb-2cc84dde698e)

**Comment by Inrixia** [comment]
@n1ckoates

**Comment by n1ckoates** [comment]
I agree that both of these should have a solid background. A solid color would look strange though, so I need to figure out a way to decrease the height of the content or "mask" it so it doesn't show behind.

**Comment by n1ckoates** [comment]
Fixed on search results, working on the tab list.

**Comment by Inrixia** [comment]
@n1ckoates Please lmk if this can be closed thx

**Comment by scopetag** [comment]
New changes to the UI present opaque/black bars once again. Noticeable in headers of albums, playlists & track radios.
![image](https://github.com/user-attachments/assets/02a2a594-42b9-413b-a536-add9b4321ccf)
![image](https://github.com/user-attachments/assets/708e53bb-d423-4538-9ba5-3f70c293913f)
