### ISSUE TITLE
Can't enable sliders

### ISSUE THREAD

**Issue by Tbirdgb** [Inrixia/neptune-plugins#7]
It's not possible to enable the sliders of both plugins, I receive this error:

![image](https://github.com/Inrixia/neptune-plugins/assets/143736149/e381b954-52dd-4227-8c0c-03f00be4de9a)

**Comment by Inrixia** [comment]
Have you tried reinstalling? Outside of that this is a Neptune issue so nothing I can really do, you would need to open a issue on https://github.com/uwu/neptune

**Comment by Tbirdgb** [comment]
Yes, i've tried that, not working.
Ok, thx, will open issue there.

**Comment by Inrixia** [comment]
Someone else had a similar issue. This should help https://github.com/uwu/neptune/issues/6
