### ISSUE TITLE
LastFM Artist Name is scrobbled incorrectly for solo artists with a comma in their name

### ISSUE THREAD

**Issue by calgod** [Inrixia/neptune-plugins#74]
Currently artist name is scrobbled by taking the first element of the artist name (split on ","):
` tags.artist?.[0]!`

### Expected example:

- "JPEGULTRA!" by "JPEGMAFIA, Denzel Curry" is scrobbled as "JPEGULTRA!" by "JPEGMAFIA.

### Unexpected/incorrect examples:

- "Tyler, The Creator" is scrobbled as "Tyler".

- "Black Country, New Road" is scrobbled as "Black Country"

- "Crosby, Stills & Nash" is scrobbled as "Crosby"

### Potential solution:

1. Add a whitelist of common artist names that contain a comma character, ','

`["Tyler, The Creator", "Black Country, New Road", "Earth, Wind & Fire", "Crosby, Stills & Nash", "Crosby, Stills, Nash & Young"]`

2. If artist name is in whitelist, scrobble as ` tags.artist?`, else ` tags.artist?.[0]!`

**Comment by Araxeus** [comment]
the specific place where it happens is:
https://github.com/Inrixia/neptune-plugins/blob/8ffd2941647a7af227ef22b8c9bc10c32de068dd/plugins/_lib/makeTags.ts#L14

personally not sure whats going on here, `neptune.currentMediaItem.item.artist.name` returns the correct name of artist so i don't know why its split by <kbd>,</kbd>

**Comment by Inrixia** [comment]
This was edge handling for the sadly fairly common occourance of tidal having tracks with multiple artists having only a single artist field with all their names comma seperated.

But since it's clearly doing more harm than good can just remove it.

**Comment by Araxeus** [comment]
> fairly common occourance

I had a quick look through my thousands of saved songs and couldn't find a single instance of this 🤷‍♂️

**Comment by Inrixia** [comment]
https://tidal.com/track/10575447?u

**Comment by Inrixia** [comment]
But yea rare enough to not worry about
