### ISSUE TITLE
[Song Downloader] Playlist download asks both folder & individual files location to download

### ISSUE THREAD

**Issue by lopes143** [Inrixia/neptune-plugins#75]
Hi. The title may not be very well written, but when downloading a playlist as a whole (3-dot selection on the playlist options, it shows "download XX tracks"), the program asks for the download folder, but also the location when downloading each song.

This is a bit redundant, because when asking the folder to put the files, it should download all songs to that folder instead of asking again for every song in the playlist.

This behaviour kinda makes the folder selection with absolutely no purpose, as well as being a bit of a pain to confirm for every file if the playlist is huge (100+ songs).

I wrote this because I though this behaviour should't be the desired one, but if it really has a reason to be like that, please let me know.
Thank you and sorry for my bad english

**Comment by Inrixia** [comment]
Ah, this will be a bug from the recent refactors fixing filename formatting.

It should only prompt for the folder once for multiple files.

For now you can set the default path in the settings to not be constantly prompted until this gets fixed.

Thanks for reporting it
