### ISSUE TITLE
TidalTags

### ISSUE THREAD

**Issue by calienyal** [Inrixia/neptune-plugins#8]
Got TidalTags installed in Tidal App W10 but can't switch it ON with the mouse operated slider:-
![image](https://github.com/Inrixia/neptune-plugins/assets/92510854/4cf6d3a8-cc4a-449e-8981-4d9281f8c362)

Colin

**Comment by Inrixia** [comment]
Is there any error that shows?

Can you try opening dev tools (CTRL-SHIFT-I) and see if there are any red errors at the bottom of the console? (Tidal itself has a bunch of yellow warnings that are always in console)

**Comment by calienyal** [comment]
\instrument.js:109 Failed to load neptune plugin!
 TypeError: Cannot read properties of undefined (reading 'startsWith')
    at Object.resolve (<anonymous>:14:17142)
    at plugins.resolve (<anonymous>:14:16662)
    at async ps (<anonymous>:14:16053)
    at async ds (<anonymous>:14:15894)
(anonymous) @ C:\Users\ColinY\AppData\Local\TIDAL\app-2.34.3\resources\original.asar\node_modules\@sentry\utils\cjs\instrument.js:109
C:\Users\ColinY\AppData\Local\TIDAL\app-2.34.3\resources\original.asar\node_modules\@sentry\utils\cjs

**Comment by Inrixia** [comment]
Sorry for the delayed response. Replied to the wrong issue. 


Someone else had a similar issue. This should help https://github.com/uwu/neptune/issues/6

**Comment by Inrixia** [comment]
Nothing I can do since it's a issue on your end. You could try opening a issue on the Neptune GitHub to see if the dev has any suggestions.

I'd also suggest trying disabling Bitdefender to see if it is actually causing the issue.

**Comment by calienyal** [comment]
Good news, the 2023.09.13 update of Tidal allows me to switch on TidalTags without disabling antivirus. The new Tidal app claims to provide more info about HiRes/MQA but TidalTags is much more informative.
Great work
Colin

**Comment by Inrixia** [comment]
Great! I'll consider this fixed then, and glad you are enjoying it :)
