### ISSUE TITLE
Share Text Plugin - QOL Request

### ISSUE THREAD

**Issue by huwie3d** [Inrixia/neptune-plugins#85]
@inrixia please bring back the old Twitter sharing text when sharing a song!!

Old : 
#NowPlaying "WalkOnBy" by NxWorries, Anderson .Paak, Knxwledge, Earl Sweatshirt, Rae Khalil on @TIDAL
https://tidal.com/browse/track/356169639?u 

New :
Listen to WalkOnBy by NxWorries, Anderson .Paak, Knxwledge, Earl Sweatshirt, Rae Khalil
https://tidal.com/browse/track/356169639?u 

or maybe custom sharing text using (?artist) (?track) (?albums)

Thank you for your work btw <3

![image](https://github.com/user-attachments/assets/ebd14ad0-5e33-4a3b-a63b-054d3634d14b)
![image](https://github.com/user-attachments/assets/fba75123-d9af-46ee-a5f1-34d41c8dd32c)

**Comment by Inrixia** [comment]
This is doable. But also I don't think there is much need for a entire plugin just for this. If there is vested interest in this from a few other people Id be happy to implement it but for now I'm closing.
