### ISSUE TITLE
Volume Scroll

### ISSUE THREAD

**Issue by gabriel-gfs** [Inrixia/neptune-plugins#89]
Would it be possible to instead of setting a fixed value for scrolling to be able to adjust this in the neptune plugin settings. I cant use it now that it is 10% as this is not granular enough causing it to be either too loud or too quiet therefore defeating the purpose of the plugin.

**Comment by Inrixia** [comment]
Yea it's super easy to add it to settings. @n1ckoates I'll assign to you but will get it done myself when I next have time if you don't get to it :)

**Comment by n1ckoates** [comment]
This is now configurable, including when holding shift.

![image](https://github.com/user-attachments/assets/c7f6c542-ea84-4eda-8d29-fe6f43ad5888)
