### ISSUE TITLE
last.fm scrobbler reports incorrect characters.

### ISSUE THREAD

**Issue by malvinael07** [Inrixia/neptune-plugins#90]
It uses a ’ instead of a ' in song titles, for example instead of 'The Ruler's Back', it scrobbles as 'The Ruler’s Back'

I've been noticing it recently. Tidal has the correct apostrophe so it seems like a scrobbling issue.

**Comment by Inrixia** [comment]
Should be a easy fix. Due to musicbrainz using that char I would guess.

Before I go replacing all instances of it with the corrected version, can you find any songs that use the other type?

**Comment by malvinael07** [comment]
> Should be a easy fix. Due to musicbrainz using that char I would guess.
> 
> Before I go replacing all instances of it with the corrected version, can you find any songs that use the other type?

https://tidal.com/browse/track/346561203?u
Scrobbles as: https://www.last.fm/music/Armand+Hammer/_/Y%E2%80%99all+Can%E2%80%99t+Stand+Right+Here

https://tidal.com/browse/track/573332?u
Scrobbles as: https://www.last.fm/music/Jadakiss/_/Cruisin%E2%80%99

**Comment by malvinael07** [comment]
If you mean songs that use ’ I can't see to find one rn

**Comment by Inrixia** [comment]
Great, I'm sure someone will open another issue if replacing them all with ' causes it's own issues.
