### ISSUE TITLE
Shazam Files Plugin Error: "Cannot read properties of undefined"

### ISSUE THREAD

**Issue by PawiX25** [Inrixia/neptune-plugins#95]
The Shazam Files plugin throws the error `"Cannot read properties of undefined (reading '__wbindgen_add_to_stack_pointer')"` when trying to recognize files. This leads to repeated failure messages without identifying the files.

**Comment by Inrixia** [comment]
Sorry for the delay on this. Have got it somewhat working but issues with Neptune are causing problems. Is this something you still want to use, shouldn't be too difficult to get it working but want to check in before spending more time on it incase you don't need it anymore.
