### ISSUE TITLE
Replace Playlist Tracks With Latest Release

### ISSUE THREAD

**Issue by Mist3rChristopher** [Inrixia/neptune-plugins#97]
This would be a slight variation to RealMAX, but instead it looks for 'upgraded' versions of songs in general - not just just in terms of quality.

For example: days, weeks or even months before an album is released, an artist will release a single, which will subsequently get added to one of my playlists. And this is where my OCD kicks in - but once the album has been released, I then scan through my playlists and replace all the singles with the album version. I also do the same thing if a remaster, expanded or deluxe edition is then later released.

If, somehow, there was a way of expanded the RealMAX search to scan tracks and playlists for newer released remasters via release date maybe, and not just the maximum quality that would be AMAZING. Super thanks!

**Comment by bbreakthrough** [comment]
Generally speaking, a so called "remaster" of an audio track is when someone makes adjustments to the original "master" file and uses more modern technology and/or techniques to improve the original audio by doing things such as cleaning up background noise, adding or subtracting particular effects, etc.

I could be wrong, but I don't get the impression this is what you mean when you say remaster in this context. 

Just trying to clarify what you're asking - are you basically saying you'd like a plugin to replace the singles versions of the tracks with the album versions when an album is released? And to replace those ones with the songs from a Deluxe album release if one is released? In the SIGNIFICANT MAJORITY of cases, the songs will be nearly identical in terms of actual bitrate, sample rate, and depth (assuming the label/person responsible for uploading the music to TIDAL doesn't massively screw up.) For the most part, the primary differences will be the cover image and the hyperlink to the album if you decided to click on it.

**Comment by Mist3rChristopher** [comment]
You've hit the nail right on the head there. 👌🏼

That is pretty much it - a plugin which would replace the original single version in the playlist, the one I would have added to a playlist weeks, often months, in advance - the one which would be showing under the EP & Singles section of Tidal with it's newest released counterpart. And like you mentioned, even though, for the best part, the only difference will be the album art and the hyperlink, unfortunately my playlists have become somewhat of an addiction, and once a track appears on an album I much prefer to have that in my playlist instead. 🙈

Trust me, it has taken over my life. 🤣

And what makes it even worse is when I've spent a lot of time swapping the tracks around, a week later a deluxe version of the album drops. I then have to replace them all again. 🤦🏻

So, for me personally, a slight variant on RealMAX in which it pulls possibly the latest release date instead of the highest quality would be a real time-saver. ⏰

**Comment by Inrixia** [comment]
The good news is under the hood RealMAX uses the isrc api tidal *provides?* (they removed the docs for it but it still works so) to lookup variations of a track.

Tracks with the same isrc are different releases of the same recording so the behavior described above of capturing releases of the same recording but not ones that differ ie remasters etc should be as easy as just sorting by release date.

**Comment by Inrixia** [comment]
@Mist3rChristopher I've added the functionality. It selects the latest track that has HiRes (ie if a newer release comes out but it does not have HiRes while a older one does it will select the older release).

This currently only applies to generating playlists and not on playback as that seems to be the use case for it.

Let me know how it goes. You will need to enable the additional functionality in the plugin settings.

**Comment by Inrixia** [comment]
I'm going to close this as completed, but if you have any questions or issues please comment here <3

**Comment by Mist3rChristopher** [comment]
@Inrixia You're a star! Thank you ever so much. And for the time it has taken. Very, very impressive. Honestly, I cannot thank you enough. I shall test-drive it imminently.
