### ISSUE TITLE
Plugin/.io links broken

### ISSUE THREAD

**Issue by Aerozol** [Inrixia/neptune-plugins#98]
All of the .io plugin links in the readme are down, for the install URL's, e.g.
`https://inrixia.github.io/neptune-plugins/ListenBrainz`

**Comment by Aerozol** [comment]
So small it's not worth opening another issue: The last.fm shortcut in the readme also does not work (https://github.com/Inrixia/neptune-plugins?tab=readme-ov-file#Last.fm)

**Comment by Inrixia** [comment]
If you are referring to them giving 404 that's normal. You need to copy paste the url into neptune to install re the guide at the top of the Readme

**Comment by Aerozol** [comment]
Oh, thank you! Feel free to close :)
