### ISSUE TITLE
Problem regarding "Song Downloader"

### ISSUE THREAD

**Issue by Leon71Mitico** [Inrixia/neptune-plugins#99]
Hi, a little while ago I tried to download an album with **2 volumes**, basically what happens is that I download only the first and the second gives me this error. I don't understand why.

![Immagine 2024-11-06 203518](https://github.com/user-attachments/assets/59e0a975-ec7c-4103-9aab-37d5d86c3ef8)

**Comment by Inrixia** [comment]
If I had to guess tidal isn't populating some Metadata as expected for tracks in the second volume. Should be a fairly easy fix, thx for reporting ❤️

**Comment by Inrixia** [comment]
I just realized you didn't link the album so I cant debug this. Please link it thx

**Comment by Leon71Mitico** [comment]
Sorry for the wait: https://tidal.com/browse/album/381031028?

But could the problem also arise with other albums?

**Comment by Inrixia** [comment]
Potentially, but specifically ones with two volumes which are a bit hard to find

**Comment by Leon71Mitico** [comment]
Hi, I'm currently still having the problem with the album in question, is there a way to fix it?

**Comment by Inrixia** [comment]
Hey, yep I haven't gotten to fixing this as I was sick all last week.

When I get it sorted this will be closed so youll know to try again.

Sorry for the delay

**Comment by senolfndk** [comment]
Where is the downloaded song I can't find it

**Comment by Inrixia** [comment]
@senolfndk if you aren't being promoted for a download path try going into your settings, putting something in the path and then clearing it again.

If that still doesn't work then try just specifying a path there.

If you need to discuss this further please open a seperate issue, or message me on the discord.

**Comment by senolfndk** [comment]
> @senolfndkEğer bir indirme yolu için terfi ettirilmiyorsanız ayarlarınıza girip, yola bir şey koyup tekrar temizlemeyi deneyin.
> 
> Eğer bu hala işe yaramazsa, sadece orada bir yol belirtmeyi deneyin.
> 
> Eğer bu konuyu daha detaylı tartışmak isterseniz lütfen ayrı bir konu açın veya bana Discord'dan mesaj atın.
I found the way to download 👍
